{% set name = 'freetds' %}
{% set version = "1.3.9" %}
{% set sha256 = "a81c8a986a7a2f0b94599ebd7a1785d72017dea6d796a7f44b6ac681ee77c2e7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://www.freetds.org/files/stable/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [arm64]
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/freetds/
    - {{ pin_subpackage('freetds') }}

requirements:
  build:
    - {{ compiler('c') }}
    - libtool  # [not win]
  host:
    - openssl
    - unixodbc  # [unix]
    - krb5      # [unix]
    - readline  # [not win]
    - make   # [not win]
    - cmake  # [win]
    - jom  # [win]
    - libiconv  # [osx]
    - perl  # [win]
  run:
    - krb5     # [unix]
    # Should be taken care of by run_exports
    # - unixodbc  # [unix]
    # - readline  # [not win]

test:
  commands:
    - tsql -C

about:
  home: http://www.freetds.org/
  license: LGPL-2.0-only
  license_file: COPYING_LIB.txt
  summary: FreeTDS is a free implementation of Sybase's DB-Library, CT-Library, and ODBC libraries
  license_family: LGPL
  doc_url: http://www.freetds.org/docs.html
  dev_url: https://github.com/FreeTDS/freetds

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
