schema_version: 1

context:
  name: freetds
  version: "1.5.9"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://www.freetds.org/files/stable/freetds-${{ version }}.tar.gz
  sha256: 955738fde3c3aad226a40be94702fbb21f16ab79fccc8b7ebeb954c4b3d0f8d4

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - pkg-config
    - if: unix
      then:
        - automake 1.17.*
        - gettext-tools
        - gnuconfig
        - make
        - libtool
    - if: win
      then:
        - cmake
        - ninja
  host:
    - openssl
    - if: unix
      then:
        - unixodbc
        - krb5
    - if: not win
      then: readline
    - if: unix
      then: libiconv
    - if: win
      then: perl
  run:
    - if: unix
      then: krb5
  run_exports:
    - ${{ pin_subpackage('freetds') }}

tests:
  - script:
      - tsql -C

about:
  license: LGPL-2.0-only
  license_file: COPYING_LIB.txt
  summary: "FreeTDS is a free implementation of Sybase's DB-Library, CT-Library, and ODBC libraries"
  homepage: http://www.freetds.org/
  repository: https://github.com/FreeTDS/freetds
  documentation: http://www.freetds.org/docs.html

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
