schema_version: 1

context:
  name: freetds
  version: 1.4.26

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/FreeTDS/freetds/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 4cd74e8134016b94b698b76eb5ad071a04a3d5ad002383a460460fdf3c57d16f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - pkg-config
    - if: unix
      then: 
        - autoconf
        - automake
        - gettext-tools
        - make
        - libtool
    - if: win
      then: cmake
    - if: win
      then: ninja
  host:
    - openssl
    - if: unix
      then: unixodbc
    - if: unix
      then: krb5
    - if: not win
      then: readline
    - if: unix
      then: libiconv
    - if: win
      then: perl
  run:
    - if: unix
      then: krb5
  run_exports:
    - ${{ pin_subpackage('freetds') }}

tests:
  - script:
      - tsql -C

about:
  license: LGPL-2.0-only
  license_file: COPYING_LIB.txt
  summary: "FreeTDS is a free implementation of Sybase's DB-Library, CT-Library, and ODBC libraries"
  homepage: http://www.freetds.org/
  repository: https://github.com/FreeTDS/freetds
  documentation: http://www.freetds.org/docs.html

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
