# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Lev3nKgv2+vOZJgYDQ9UnPpC8mtcFyctA4uKtUd9jLfwWYDdBfCPIjScJ7ll8JUUDpJ61Pzzr9bwWhwS29GIOkgp8vAhXuR4D0Kf8Z30uCJBOEsuYrCgyMzA1xk1CK2GyzV68FjgSaZHrGqt1+vMqqeKqjOgwsFsB8STAzCUGp+GP5nGTxUjtonsEnNBHu4knXtmKp4Kjby+bDNwK3FgEi44yPE4LQbov9teMa6IP9Pg27QJf/H3EpOb/m3Tx2GFw4YDMRAHAVUjNw9Mdx8C1z/LnRz/S5O4B9FxgQdcDKIL7Dij5RWI1op6AgKzav+K6JdkmSr0itAB5fbfYLP1LRQnGYu8+ofXwLfnlsCAc00OrXynyfxkCmTM/5V9muUSmaBmFdOxpWJJDxCOu/JWnZFubYeHMDBq33w9Cn+N+ujkNfqsFL5K7vaWsWU1kGSdF5Llh8xH9PpzPGy8G2alkdcFeRz8A9zqiULDFrDMY5Oqo+xS+LathM0aDVzV1HgVYgVRg8HHr+MzpxVD8qqRgZ8ThjtXh4HxbulBkouBQ39JOtlYyGs8G3FYovgQ2QeXJ81PJ3OKSmIQsOHPpeqbTY5k51v7aOFQmoH9VIsPJnnsLzuEhny+Qn4lcokCl48TRwArnI74AvRckAFHP7wElbE+IDavXRQVI7R7ugoDwuA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
