appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pebmMmSQtC7l7sYTFD8Xfiy6wFMkRq1v1HoopFHvVy/fz4f4RekuTsWKEAj+XO4otnUuOaPOkDWY1FGQRqijOEcEAU5W7p8MexnZuBvO9TH1bO28NKtHR09zRyTijBBOd7ySOOZ82Se5otVAuU52pqegjCnUAKpUj4mpJchiD4dPeZcI42sMu15QqEnPGlx9Fp7V5gHhLSQNI68gWK1x4F/PFT6KVceQxiA2SKJdz+yeEx9T37B4m+2yE16MOPm+pTsXz8LrEl+E6GQoFHyWAPxU8A3Oo0LEVT4v6Biv1Llt2an2V4CddXRQNpjhQsyLzy+0qF4+XP3hBYNO8cO+NA9J3jsaYIRiEWJHtYMQJZLAAeGhwLtDhmo/lCnFq0s4pveX0Pl/lR2Uei9HqDg8gcO4h6BGuRp0qmv2RvDwRgtyAYSNj97hsbz/xWBJODWTicvdYZPNln5vqV3OEEbJjDLxF6eJcansBngo2zqGQcqyYuCPZDDyblacQ9RJzEATfOaUBYcDgbpLhuImK1VVqgmHui2u1VIHKUneqtyPTAkVdbq7MApN5juYbIof/tkP+2cI2eom243tYs1w+1tWZvMyLu+gci/2uvLoq4XW+n8gwse9hCpc6eapcSLIhyTGamy1rNjVIHWVYZp0ELIBDVOyn6wWjWQG/4k3jXyddL8=}
